### PR TITLE
chore(deps): remove pkg already in unocss

### PR DESCRIPTION
**Pull request by maninak**
As shown in [packages/readme](https://github.com/antfu/unocss/blob/134150039784a2110404e0a6d9622580cbc716f2/packages/README.md) `@unocss/preset-icons` is already included in `unocss`

### CODE REVIEW

**Comment by antfu** [comment]
It was not - so we might also need to bump the versions

**Comment by maninak** [comment]
Unless I messed it up during testing, the icons were still showing after I removed `@unocss/preset-icons`.

I opted to not bump other dependencies to avoid breaking things, but I'll do it if you say you want me to.

**Comment by antfu** [comment]
The breakings are mostly the internal APIs and won't affect on userland

**Comment by maninak** [comment]
I tried upgrading to `"@unocss/nuxt": "^0.9.3"` but if I serve the app it shows in the browser:

image

The PR as is now with just 358bc81241cc3edb5b136398a720d10dd64d4875 seems to have no issues with icons.

image

**Pull request merged**
